apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ciceruesi
  description: .NET MVC app
  annotations:
   backstage.io/techdocs-ref: value
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: drensokoli
