apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: ciceruesi
  description: .NET MVC app
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: drensokoli
