site_name: 'Ciceruesi'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/drensokoli/Ciceruesi

plugins:
  - techdocs-core

nav:
  - Overview:
      - What is Backstage?: 'index.md'
